name: Validate with HACS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
