name: Validate with hassfest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - uses: "home-assistant/actions/hassfest@master"
